# Generated by Django 2.2 on 2019-06-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20190605_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteFile',
            new_name='Note',
        ),
    ]
