# Generated by Django 2.2 on 2019-06-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
