# Generated by Django 2.2 on 2019-06-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20190606_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(),
        ),
    ]
